name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          sudo apt install -y git python3-pip python3-dev python3-setuptools python3-wheel python3-venv
          sudo apt install -y libltdl-dev libffi-dev libssl-dev python3-kivy

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user cython==0.29.33
          pip install --user buildozer

      - name: Add buildozer to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Accept Android SDK licenses
        run: |
          mkdir -p $HOME/.android
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.android/repositories.cfg
          yes | $HOME/.local/bin/buildozer android update || true

      - name: Build debug APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
        if: success()

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: .buildozer/
        if: failure()

