name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip libncurses5
          pip3 install --upgrade pip
          pip3 install --user cython buildozer

      - name: Add buildozer to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: notesapp-apk
          path: bin/*.apk
