name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip openjdk-17-jdk python3-pip libncurses5-dev
          pip3 install --upgrade pip
          pip3 install --user cython buildozer

      - name: Add buildozer to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
